# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_dingdan.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 350)
        self.setMaximumSize(624, 350)
        self.setMinimumSize(624, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 781, 531))
        self.label.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 260, 481, 21))
        self.lineEdit.setMinimumSize(QtCore.QSize(481, 21))
        self.lineEdit.setMaximumSize(QtCore.QSize(481, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEnabled(False)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(330, 130, 72, 15))
        self.label_27.setMinimumSize(QtCore.QSize(72, 15))
        self.label_27.setMaximumSize(QtCore.QSize(72, 15))
        self.label_27.setObjectName("label_27")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(330, 80, 72, 15))
        self.label_22.setMinimumSize(QtCore.QSize(72, 15))
        self.label_22.setMaximumSize(QtCore.QSize(72, 15))
        self.label_22.setObjectName("label_22")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 260, 72, 15))
        self.label_29.setMinimumSize(QtCore.QSize(72, 15))
        self.label_29.setMaximumSize(QtCore.QSize(72, 15))
        self.label_29.setObjectName("label_29")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(50, 30, 31, 15))
        self.label_26.setMinimumSize(QtCore.QSize(31, 15))
        self.label_26.setMaximumSize(QtCore.QSize(31, 15))
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(330, 30, 72, 15))
        self.label_24.setMinimumSize(QtCore.QSize(72, 15))
        self.label_24.setMaximumSize(QtCore.QSize(72, 15))
        self.label_24.setObjectName("label_24")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(330, 170, 72, 15))
        self.label_20.setMinimumSize(QtCore.QSize(72, 15))
        self.label_20.setMaximumSize(QtCore.QSize(72, 15))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(50, 210, 31, 15))
        self.label_21.setMinimumSize(QtCore.QSize(31, 15))
        self.label_21.setMaximumSize(QtCore.QSize(31, 15))
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(50, 80, 31, 15))
        self.label_25.setMinimumSize(QtCore.QSize(31, 15))
        self.label_25.setMaximumSize(QtCore.QSize(31, 15))
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(50, 130, 31, 15))
        self.label_28.setMinimumSize(QtCore.QSize(31, 15))
        self.label_28.setMaximumSize(QtCore.QSize(31, 15))
        self.label_28.setObjectName("label_28")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(50, 170, 31, 15))
        self.label_23.setMinimumSize(QtCore.QSize(31, 15))
        self.label_23.setMaximumSize(QtCore.QSize(31, 15))
        self.label_23.setObjectName("label_23")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 30, 181, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(110, 170, 181, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 210, 181, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 80, 181, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 130, 181, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(410, 130, 181, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(410, 80, 181, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(410, 30, 181, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(410, 170, 181, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_12.setEnabled(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_27.setText(_translate("MainWindow", "房型"))
        self.label_22.setText(_translate("MainWindow", "建造年代"))
        self.label_29.setText(_translate("MainWindow", "详细地址"))
        self.label_26.setText(_translate("MainWindow", "区域"))
        self.label_24.setText(_translate("MainWindow", "房屋类型"))
        self.label_20.setText(_translate("MainWindow", "朝向"))
        self.label_21.setText(_translate("MainWindow", "装修"))
        self.label_25.setText(_translate("MainWindow", "售价"))
        self.label_28.setText(_translate("MainWindow", "面积"))
        self.label_23.setText(_translate("MainWindow", "楼层"))

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)

    def setup(self, res):
        self.lineEdit_5.setText(res[0])
        self.lineEdit_9.setText(res[1])
        self.lineEdit_4.setText(res[2])
        self.lineEdit_10.setText(res[3])
        self.lineEdit_6.setText(res[4])
        self.lineEdit_11.setText(res[5])
        self.lineEdit_7.setText(res[6])
        self.lineEdit_12.setText(res[7])
        self.lineEdit_8.setText(res[8])
        self.lineEdit.setText(res[9])


import b_rc
