# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
import sys

import pymysql
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import check
import config
import display_dingdan
import send
from QQLabel import QQLabel
from QQPushButton import QQPushButton


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1015, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1015, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 60, 151, 481))
        self.toolBox.setMinimumSize(QtCore.QSize(151, 481))
        self.toolBox.setMaximumSize(QtCore.QSize(151, 481))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 151, 391))
        self.page.setObjectName("page")
        self.pushButton = QQPushButton(1, self.page)
        self.pushButton.setGeometry(QtCore.QRect(0, 7, 151, 31))
        self.pushButton.setMinimumSize(QtCore.QSize(151, 31))
        self.pushButton.setMaximumSize(QtCore.QSize(151, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QQPushButton(2, self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 40, 151, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(151, 31))
        self.pushButton_2.setMaximumSize(QtCore.QSize(151, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 151, 391))
        self.page_2.setObjectName("page_2")
        self.pushButton_14 = QQPushButton(3, self.page_2)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 0, 151, 28))
        self.pushButton_14.setMinimumSize(QtCore.QSize(151, 28))
        self.pushButton_14.setMaximumSize(QtCore.QSize(151, 28))
        self.pushButton_14.setObjectName("pushButton_14")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 151, 391))
        self.page_3.setObjectName("page_3")
        self.pushButton_6 = QQPushButton(5, self.page_3)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 30, 151, 28))
        self.pushButton_6.setMinimumSize(QtCore.QSize(151, 28))
        self.pushButton_6.setMaximumSize(QtCore.QSize(151, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QQPushButton(4, self.page_3)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 151, 28))
        self.pushButton_5.setMinimumSize(QtCore.QSize(151, 28))
        self.pushButton_5.setMaximumSize(QtCore.QSize(151, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.toolBox.addItem(self.page_3, "")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 60, 831, 481))
        self.stackedWidget.setMinimumSize(QtCore.QSize(831, 481))
        self.stackedWidget.setMaximumSize(QtCore.QSize(831, 481))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(250, 20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 801, 481))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_2 = QtWidgets.QLabel(self.page_6)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 31, 15))
        self.label_2.setMinimumSize(QtCore.QSize(31, 15))
        self.label_2.setMaximumSize(QtCore.QSize(31, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(390, 80, 72, 15))
        self.label_3.setMinimumSize(QtCore.QSize(72, 15))
        self.label_3.setMaximumSize(QtCore.QSize(72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 801, 481))
        self.label_4.setMinimumSize(QtCore.QSize(801, 481))
        self.label_4.setMaximumSize(QtCore.QSize(801, 481))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.page_6)
        self.label_7.setGeometry(QtCore.QRect(340, 20, 131, 41))
        self.label_7.setMinimumSize(QtCore.QSize(131, 41))
        self.label_7.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.page_6)
        self.comboBox.setGeometry(QtCore.QRect(470, 80, 191, 22))
        self.comboBox.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 80, 181, 22))
        self.comboBox_2.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_2.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(110, 130, 31, 15))
        self.label_13.setMinimumSize(QtCore.QSize(31, 15))
        self.label_13.setMaximumSize(QtCore.QSize(31, 15))
        self.label_13.setObjectName("label_13")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 130, 181, 22))
        self.comboBox_3.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_3.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setGeometry(QtCore.QRect(390, 130, 72, 15))
        self.label_14.setMinimumSize(QtCore.QSize(72, 15))
        self.label_14.setMaximumSize(QtCore.QSize(72, 15))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setGeometry(QtCore.QRect(110, 180, 31, 15))
        self.label_15.setMinimumSize(QtCore.QSize(31, 15))
        self.label_15.setMaximumSize(QtCore.QSize(31, 15))
        self.label_15.setObjectName("label_15")
        self.comboBox_5 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 180, 181, 22))
        self.comboBox_5.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_5.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setGeometry(QtCore.QRect(390, 180, 72, 15))
        self.label_16.setMinimumSize(QtCore.QSize(72, 15))
        self.label_16.setMaximumSize(QtCore.QSize(72, 15))
        self.label_16.setObjectName("label_16")
        self.comboBox_7 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_7.setGeometry(QtCore.QRect(470, 130, 191, 22))
        self.comboBox_7.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_7.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_8.setGeometry(QtCore.QRect(470, 180, 191, 22))
        self.comboBox_8.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_8.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(110, 220, 31, 15))
        self.label_17.setMinimumSize(QtCore.QSize(31, 15))
        self.label_17.setMaximumSize(QtCore.QSize(31, 15))
        self.label_17.setObjectName("label_17")
        self.comboBox_6 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_6.setGeometry(QtCore.QRect(180, 220, 181, 22))
        self.comboBox_6.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_6.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setGeometry(QtCore.QRect(390, 220, 72, 15))
        self.label_18.setMinimumSize(QtCore.QSize(72, 15))
        self.label_18.setMaximumSize(QtCore.QSize(72, 15))
        self.label_18.setObjectName("label_18")
        self.comboBox_9 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_9.setGeometry(QtCore.QRect(470, 220, 191, 22))
        self.comboBox_9.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_9.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(110, 260, 31, 15))
        self.label_19.setMinimumSize(QtCore.QSize(31, 15))
        self.label_19.setMaximumSize(QtCore.QSize(31, 15))
        self.label_19.setObjectName("label_19")
        self.comboBox_10 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_10.setGeometry(QtCore.QRect(180, 260, 181, 22))
        self.comboBox_10.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_10.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.label_13.raise_()
        self.comboBox_3.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.comboBox_5.raise_()
        self.label_16.raise_()
        self.comboBox_7.raise_()
        self.comboBox_8.raise_()
        self.label_17.raise_()
        self.comboBox_6.raise_()
        self.label_18.raise_()
        self.comboBox_9.raise_()
        self.label_19.raise_()
        self.comboBox_10.raise_()
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_9 = QtWidgets.QLabel(self.page_7)
        self.label_9.setGeometry(QtCore.QRect(20, 0, 801, 481))
        self.label_9.setMinimumSize(QtCore.QSize(801, 481))
        self.label_9.setMaximumSize(QtCore.QSize(801, 481))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.page_7)
        self.label_12.setGeometry(QtCore.QRect(340, 20, 131, 41))
        self.label_12.setMinimumSize(QtCore.QSize(131, 41))
        self.label_12.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.comboBox_11 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_11.setGeometry(QtCore.QRect(470, 140, 191, 22))
        self.comboBox_11.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_11.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_20 = QtWidgets.QLabel(self.page_7)
        self.label_20.setGeometry(QtCore.QRect(390, 230, 72, 15))
        self.label_20.setMinimumSize(QtCore.QSize(72, 15))
        self.label_20.setMaximumSize(QtCore.QSize(72, 15))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setGeometry(QtCore.QRect(110, 270, 31, 15))
        self.label_21.setMinimumSize(QtCore.QSize(31, 15))
        self.label_21.setMaximumSize(QtCore.QSize(31, 15))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_7)
        self.label_22.setGeometry(QtCore.QRect(390, 140, 72, 15))
        self.label_22.setMinimumSize(QtCore.QSize(72, 15))
        self.label_22.setMaximumSize(QtCore.QSize(72, 15))
        self.label_22.setObjectName("label_22")
        self.comboBox_12 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_12.setGeometry(QtCore.QRect(470, 190, 191, 22))
        self.comboBox_12.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_12.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 90, 181, 22))
        self.comboBox_4.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_4.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_13 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_13.setGeometry(QtCore.QRect(180, 190, 181, 22))
        self.comboBox_13.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_13.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.label_23 = QtWidgets.QLabel(self.page_7)
        self.label_23.setGeometry(QtCore.QRect(110, 230, 31, 15))
        self.label_23.setMinimumSize(QtCore.QSize(31, 15))
        self.label_23.setMaximumSize(QtCore.QSize(31, 15))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_7)
        self.label_24.setGeometry(QtCore.QRect(390, 90, 72, 15))
        self.label_24.setMinimumSize(QtCore.QSize(72, 15))
        self.label_24.setMaximumSize(QtCore.QSize(72, 15))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page_7)
        self.label_25.setGeometry(QtCore.QRect(110, 140, 31, 15))
        self.label_25.setMinimumSize(QtCore.QSize(31, 15))
        self.label_25.setMaximumSize(QtCore.QSize(31, 15))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_7)
        self.label_26.setGeometry(QtCore.QRect(110, 90, 31, 15))
        self.label_26.setMinimumSize(QtCore.QSize(31, 15))
        self.label_26.setMaximumSize(QtCore.QSize(31, 15))
        self.label_26.setObjectName("label_26")
        self.comboBox_14 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_14.setGeometry(QtCore.QRect(470, 230, 191, 22))
        self.comboBox_14.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_14.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_15.setGeometry(QtCore.QRect(470, 90, 191, 22))
        self.comboBox_15.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_15.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.label_27 = QtWidgets.QLabel(self.page_7)
        self.label_27.setGeometry(QtCore.QRect(390, 190, 72, 15))
        self.label_27.setMinimumSize(QtCore.QSize(72, 15))
        self.label_27.setMaximumSize(QtCore.QSize(72, 15))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.page_7)
        self.label_28.setGeometry(QtCore.QRect(110, 190, 31, 15))
        self.label_28.setMinimumSize(QtCore.QSize(31, 15))
        self.label_28.setMaximumSize(QtCore.QSize(31, 15))
        self.label_28.setObjectName("label_28")
        self.comboBox_16 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_16.setGeometry(QtCore.QRect(180, 270, 181, 22))
        self.comboBox_16.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_16.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_17 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_17.setGeometry(QtCore.QRect(180, 230, 181, 22))
        self.comboBox_17.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_17.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_18.setGeometry(QtCore.QRect(180, 140, 181, 22))
        self.comboBox_18.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_18.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.lineEdit = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit.setGeometry(QtCore.QRect(180, 320, 481, 21))
        self.lineEdit.setMinimumSize(QtCore.QSize(481, 21))
        self.lineEdit.setMaximumSize(QtCore.QSize(481, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_29 = QtWidgets.QLabel(self.page_7)
        self.label_29.setGeometry(QtCore.QRect(80, 320, 72, 15))
        self.label_29.setMinimumSize(QtCore.QSize(72, 15))
        self.label_29.setMaximumSize(QtCore.QSize(72, 15))
        self.label_29.setObjectName("label_29")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_10 = QtWidgets.QLabel(self.page_8)
        self.label_10.setGeometry(QtCore.QRect(20, 0, 801, 481))
        self.label_10.setMinimumSize(QtCore.QSize(801, 481))
        self.label_10.setMaximumSize(QtCore.QSize(801, 481))
        self.label_10.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_30 = QtWidgets.QLabel(self.page_8)
        self.label_30.setGeometry(QtCore.QRect(360, 20, 131, 41))
        self.label_30.setMinimumSize(QtCore.QSize(131, 41))
        self.label_30.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_46 = QtWidgets.QLabel(self.page_8)
        self.label_46.setGeometry(QtCore.QRect(60, 390, 72, 15))
        self.label_46.setMinimumSize(QtCore.QSize(72, 15))
        self.label_46.setMaximumSize(QtCore.QSize(72, 15))
        self.label_46.setObjectName("label_46")
        self.textEdit = QtWidgets.QTextEdit(self.page_8)
        self.textEdit.setGeometry(QtCore.QRect(120, 350, 531, 111))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_12.setGeometry(QtCore.QRect(660, 70, 93, 28))
        self.pushButton_12.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_12.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_13.setGeometry(QtCore.QRect(660, 110, 93, 28))
        self.pushButton_13.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_13.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_16.setGeometry(QtCore.QRect(660, 150, 93, 28))
        self.pushButton_16.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_16.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_63 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_63.setGeometry(QtCore.QRect(660, 190, 93, 28))
        self.pushButton_63.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_63.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_63.setText('显示订单')
        self.pushButton_63.clicked.connect(self.slot_display_dingdan)
        self.pushButton_64 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_64.setGeometry(QtCore.QRect(660, 230, 93, 28))
        self.pushButton_64.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_64.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_64.setText('发送信息')
        self.pushButton_65 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_65.setGeometry(QtCore.QRect(660, 270, 93, 28))
        self.pushButton_65.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_65.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_65.setText('完成订单')
        self.pushButton_64.clicked.connect(self.slot_open_send)
        self.pushButton_65.clicked.connect(self.slot_acce_dingdan)
        self.listWidget_2 = QtWidgets.QListWidget(self.page_8)
        self.listWidget_2.setGeometry(QtCore.QRect(120, 60, 531, 281))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 360, 101, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_28 = QtWidgets.QComboBox(self.page_8)
        self.comboBox_28.setGeometry(QtCore.QRect(660, 30, 91, 22))
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.label_11 = QtWidgets.QLabel(self.page_8)
        self.label_11.setGeometry(QtCore.QRect(580, 30, 72, 15))
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_8)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setGeometry(QtCore.QRect(20, 0, 801, 481))
        self.label_32.setMinimumSize(QtCore.QSize(801, 481))
        self.label_32.setMaximumSize(QtCore.QSize(801, 481))
        self.label_32.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_4)
        self.label_33.setGeometry(QtCore.QRect(320, 30, 201, 41))
        self.label_33.setMinimumSize(QtCore.QSize(201, 41))
        self.label_33.setMaximumSize(QtCore.QSize(201, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_47 = QtWidgets.QLabel(self.page_4)
        self.label_47.setGeometry(QtCore.QRect(101, 430, 61, 20))
        self.label_47.setMinimumSize(QtCore.QSize(61, 20))
        self.label_47.setMaximumSize(QtCore.QSize(61, 20))
        self.label_47.setObjectName("label_47")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 430, 481, 21))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(481, 21))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(481, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_48 = QtWidgets.QLabel(self.page_4)
        self.label_48.setGeometry(QtCore.QRect(130, 400, 31, 15))
        self.label_48.setMinimumSize(QtCore.QSize(31, 15))
        self.label_48.setMaximumSize(QtCore.QSize(31, 15))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.page_4)
        self.label_49.setGeometry(QtCore.QRect(410, 360, 72, 15))
        self.label_49.setMinimumSize(QtCore.QSize(72, 15))
        self.label_49.setMaximumSize(QtCore.QSize(72, 15))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.page_4)
        self.label_50.setGeometry(QtCore.QRect(130, 240, 31, 15))
        self.label_50.setMinimumSize(QtCore.QSize(31, 15))
        self.label_50.setMaximumSize(QtCore.QSize(31, 15))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.page_4)
        self.label_51.setGeometry(QtCore.QRect(410, 400, 72, 15))
        self.label_51.setMinimumSize(QtCore.QSize(72, 15))
        self.label_51.setMaximumSize(QtCore.QSize(72, 15))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_4)
        self.label_52.setGeometry(QtCore.QRect(410, 320, 72, 15))
        self.label_52.setMinimumSize(QtCore.QSize(72, 15))
        self.label_52.setMaximumSize(QtCore.QSize(72, 15))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.page_4)
        self.label_53.setGeometry(QtCore.QRect(130, 280, 31, 15))
        self.label_53.setMinimumSize(QtCore.QSize(31, 15))
        self.label_53.setMaximumSize(QtCore.QSize(31, 15))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_4)
        self.label_54.setGeometry(QtCore.QRect(130, 320, 31, 15))
        self.label_54.setMinimumSize(QtCore.QSize(31, 15))
        self.label_54.setMaximumSize(QtCore.QSize(31, 15))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_4)
        self.label_55.setGeometry(QtCore.QRect(410, 280, 72, 15))
        self.label_55.setMinimumSize(QtCore.QSize(72, 15))
        self.label_55.setMaximumSize(QtCore.QSize(72, 15))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_4)
        self.label_56.setGeometry(QtCore.QRect(130, 360, 31, 15))
        self.label_56.setMinimumSize(QtCore.QSize(31, 15))
        self.label_56.setMaximumSize(QtCore.QSize(31, 15))
        self.label_56.setObjectName("label_56")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_15.setGeometry(QtCore.QRect(600, 90, 93, 28))
        self.pushButton_15.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_15.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_17 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_17.setGeometry(QtCore.QRect(600, 130, 93, 28))
        self.pushButton_17.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_17.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_18.setGeometry(QtCore.QRect(600, 170, 93, 28))
        self.pushButton_18.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_18.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 280, 181, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 240, 181, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 320, 181, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 360, 181, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 400, 181, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(490, 280, 181, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(490, 320, 181, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(490, 360, 181, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(490, 400, 181, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.listWidget = QtWidgets.QListWidget(self.page_4)
        self.listWidget.setGeometry(QtCore.QRect(130, 80, 461, 151))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 240, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_4)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_34 = QtWidgets.QLabel(self.page_10)
        self.label_34.setGeometry(QtCore.QRect(20, 0, 801, 481))
        self.label_34.setMinimumSize(QtCore.QSize(801, 481))
        self.label_34.setMaximumSize(QtCore.QSize(801, 481))
        self.label_34.setStyleSheet("background-image: url(:/newPrefix/59350c3c70152_1024.jpg);")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.page_10)
        self.label_35.setGeometry(QtCore.QRect(350, 30, 141, 41))
        self.label_35.setMinimumSize(QtCore.QSize(141, 41))
        self.label_35.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_10)
        self.label_36.setGeometry(QtCore.QRect(410, 210, 72, 15))
        self.label_36.setMinimumSize(QtCore.QSize(72, 15))
        self.label_36.setMaximumSize(QtCore.QSize(72, 15))
        self.label_36.setObjectName("label_36")
        self.comboBox_19 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_19.setGeometry(QtCore.QRect(490, 120, 191, 22))
        self.comboBox_19.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_19.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_19.setObjectName("comboBox_19")
        self.label_37 = QtWidgets.QLabel(self.page_10)
        self.label_37.setGeometry(QtCore.QRect(410, 70, 72, 15))
        self.label_37.setMinimumSize(QtCore.QSize(72, 15))
        self.label_37.setMaximumSize(QtCore.QSize(72, 15))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page_10)
        self.label_38.setGeometry(QtCore.QRect(101, 300, 61, 20))
        self.label_38.setMinimumSize(QtCore.QSize(61, 20))
        self.label_38.setMaximumSize(QtCore.QSize(61, 20))
        self.label_38.setObjectName("label_38")
        self.comboBox_20 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_20.setGeometry(QtCore.QRect(200, 210, 181, 22))
        self.comboBox_20.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_20.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_20.setObjectName("comboBox_20")
        self.label_39 = QtWidgets.QLabel(self.page_10)
        self.label_39.setGeometry(QtCore.QRect(410, 170, 72, 15))
        self.label_39.setMinimumSize(QtCore.QSize(72, 15))
        self.label_39.setMaximumSize(QtCore.QSize(72, 15))
        self.label_39.setObjectName("label_39")
        self.comboBox_21 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_21.setGeometry(QtCore.QRect(200, 170, 181, 22))
        self.comboBox_21.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_21.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_21.setObjectName("comboBox_21")
        self.label_40 = QtWidgets.QLabel(self.page_10)
        self.label_40.setGeometry(QtCore.QRect(130, 250, 31, 15))
        self.label_40.setMinimumSize(QtCore.QSize(31, 15))
        self.label_40.setMaximumSize(QtCore.QSize(31, 15))
        self.label_40.setObjectName("label_40")
        self.comboBox_22 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_22.setGeometry(QtCore.QRect(490, 210, 191, 22))
        self.comboBox_22.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_22.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_22.setObjectName("comboBox_22")
        self.label_41 = QtWidgets.QLabel(self.page_10)
        self.label_41.setGeometry(QtCore.QRect(130, 170, 31, 15))
        self.label_41.setMinimumSize(QtCore.QSize(31, 15))
        self.label_41.setMaximumSize(QtCore.QSize(31, 15))
        self.label_41.setObjectName("label_41")
        self.comboBox_23 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_23.setGeometry(QtCore.QRect(200, 70, 181, 22))
        self.comboBox_23.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_23.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_24 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_24.setGeometry(QtCore.QRect(490, 70, 191, 22))
        self.comboBox_24.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_24.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_25 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_25.setGeometry(QtCore.QRect(200, 120, 181, 22))
        self.comboBox_25.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_25.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_26 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_26.setGeometry(QtCore.QRect(490, 170, 191, 22))
        self.comboBox_26.setMinimumSize(QtCore.QSize(191, 22))
        self.comboBox_26.setMaximumSize(QtCore.QSize(191, 22))
        self.comboBox_26.setObjectName("comboBox_26")
        self.label_42 = QtWidgets.QLabel(self.page_10)
        self.label_42.setGeometry(QtCore.QRect(130, 70, 31, 15))
        self.label_42.setMinimumSize(QtCore.QSize(31, 15))
        self.label_42.setMaximumSize(QtCore.QSize(31, 15))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.page_10)
        self.label_43.setGeometry(QtCore.QRect(410, 120, 72, 15))
        self.label_43.setMinimumSize(QtCore.QSize(72, 15))
        self.label_43.setMaximumSize(QtCore.QSize(72, 15))
        self.label_43.setObjectName("label_43")
        self.comboBox_27 = QtWidgets.QComboBox(self.page_10)
        self.comboBox_27.setGeometry(QtCore.QRect(200, 250, 181, 22))
        self.comboBox_27.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_27.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_27.setObjectName("comboBox_27")
        self.label_44 = QtWidgets.QLabel(self.page_10)
        self.label_44.setGeometry(QtCore.QRect(130, 210, 31, 15))
        self.label_44.setMinimumSize(QtCore.QSize(31, 15))
        self.label_44.setMaximumSize(QtCore.QSize(31, 15))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.page_10)
        self.label_45.setGeometry(QtCore.QRect(130, 120, 31, 15))
        self.label_45.setMinimumSize(QtCore.QSize(31, 15))
        self.label_45.setMaximumSize(QtCore.QSize(31, 15))
        self.label_45.setObjectName("label_45")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 300, 481, 21))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(481, 21))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(481, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 370, 93, 28))
        self.pushButton_7.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_7.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_61 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_61.setGeometry(QtCore.QRect(370, 370, 93, 28))
        self.pushButton_61.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_61.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_61.setText('上传')
        self.pushButton_62 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_62.setGeometry(QtCore.QRect(370, 370, 93, 28))
        self.pushButton_62.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_62.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_62.setText('上传')
        self.stackedWidget.addWidget(self.page_10)
        self.label_5 = QQLabel('头像', self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.label_5.setMinimumSize(QtCore.QSize(51, 51))
        self.label_5.setMaximumSize(QtCore.QSize(51, 51))
        self.label_5.setStyleSheet("image: url(:/newPrefix/62386374_p0.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QQLabel('用户栏', self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 0, 121, 51))
        self.label_6.setMinimumSize(QtCore.QSize(121, 51))
        self.label_6.setMaximumSize(QtCore.QSize(121, 51))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.slot_set_page)
        self.pushButton_2.clicked.connect(MainWindow.slot_set_page)
        self.pushButton_14.clicked.connect(MainWindow.slot_set_page)
        self.pushButton_5.clicked.connect(MainWindow.slot_set_page)
        self.pushButton_6.clicked.connect(MainWindow.slot_set_page)
        self.pushButton_13.clicked.connect(MainWindow.slot_up)
        self.pushButton_12.clicked.connect(MainWindow.slot_delitem_2)
        self.pushButton_16.clicked.connect(MainWindow.slot_down)
        self.pushButton_17.clicked.connect(MainWindow.slot_delitem)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "上传需求"))
        self.pushButton_2.setText(_translate("MainWindow", "上传房源"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "咨询房源"))
        self.pushButton_14.setText(_translate("MainWindow", "通知"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "通知"))
        self.pushButton_6.setText(_translate("MainWindow", "查询房源"))
        self.pushButton_5.setText(_translate("MainWindow", "验证房源信息"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "管理房源"))
        self.label.setText(_translate("MainWindow", "欢迎使用房屋中介系统"))
        self.label_2.setText(_translate("MainWindow", "区域"))
        self.label_3.setText(_translate("MainWindow", "房屋类型"))
        self.label_7.setText(_translate("MainWindow", "上传需求"))
        self.comboBox.setItemText(0, _translate("MainWindow", "普通住宅"))
        self.comboBox.setItemText(1, _translate("MainWindow", "公寓"))
        self.comboBox.setItemText(2, _translate("MainWindow", "平房"))
        self.comboBox.setItemText(3, _translate("MainWindow", "别墅"))
        self.comboBox.setItemText(4, _translate("MainWindow", "其他"))
        self.label_13.setText(_translate("MainWindow", "售价"))
        self.label_14.setText(_translate("MainWindow", "建造年代"))
        self.label_15.setText(_translate("MainWindow", "面积"))
        self.label_16.setText(_translate("MainWindow", "房型"))
        self.label_17.setText(_translate("MainWindow", "楼层"))
        self.label_18.setText(_translate("MainWindow", "朝向"))
        self.label_19.setText(_translate("MainWindow", "交通"))
        self.label_12.setText(_translate("MainWindow", "上传房源"))
        self.label_20.setText(_translate("MainWindow", "朝向"))
        self.label_21.setText(_translate("MainWindow", "交通"))
        self.label_22.setText(_translate("MainWindow", "建造年代"))
        self.label_23.setText(_translate("MainWindow", "楼层"))
        self.label_24.setText(_translate("MainWindow", "房屋类型"))
        self.label_25.setText(_translate("MainWindow", "售价"))
        self.label_26.setText(_translate("MainWindow", "区域"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "普通住宅"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "公寓"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "平房"))
        self.comboBox_15.setItemText(3, _translate("MainWindow", "别墅"))
        self.comboBox_15.setItemText(4, _translate("MainWindow", "其他"))
        self.label_27.setText(_translate("MainWindow", "房型"))
        self.label_28.setText(_translate("MainWindow", "面积"))
        self.label_29.setText(_translate("MainWindow", "详细地址"))
        self.label_30.setText(_translate("MainWindow", "通知"))
        self.label_46.setText(_translate("MainWindow", "信息:"))
        self.pushButton_12.setText(_translate("MainWindow", "删除"))
        self.pushButton_13.setText(_translate("MainWindow", "上移"))
        self.pushButton_16.setText(_translate("MainWin dow", "下移"))
        self.pushButton_4.setText(_translate("MainWindow", "根据订单查询"))
        self.comboBox_28.setItemText(0, _translate("MainWindow", "时间"))
        self.comboBox_28.setItemText(1, _translate("MainWindow", "未完成订单"))
        self.comboBox_28.setItemText(2, _translate("MainWindow", "用户"))
        self.comboBox_28.addItem('完成订单')
        self.label_11.setText(_translate("MainWindow", "排序:"))
        self.label_33.setText(_translate("MainWindow", "验证房源信息"))
        self.label_47.setText(_translate("MainWindow", "详细地址"))
        self.lineEdit_3.setText(_translate("MainWindow", "单独给出会根据所给的信息含有的关键字查询相关房源"))
        self.label_48.setText(_translate("MainWindow", "交通"))
        self.label_49.setText(_translate("MainWindow", "房型"))
        self.label_50.setText(_translate("MainWindow", "区域"))
        self.label_51.setText(_translate("MainWindow", "朝向"))
        self.label_52.setText(_translate("MainWindow", "建造年代"))
        self.label_53.setText(_translate("MainWindow", "售价"))
        self.label_54.setText(_translate("MainWindow", "面积"))
        self.label_55.setText(_translate("MainWindow", "房屋类型"))
        self.label_56.setText(_translate("MainWindow", "楼层"))
        self.pushButton_15.setText(_translate("MainWindow", "还原"))
        self.pushButton_17.setText(_translate("MainWindow", "删除"))
        self.pushButton_18.setText(_translate("MainWindow", "确认"))
        self.pushButton_3.setText(_translate("MainWindow", "修改"))
        self.label_35.setText(_translate("MainWindow", "查询房源"))
        self.label_36.setText(_translate("MainWindow", "朝向"))
        self.label_37.setText(_translate("MainWindow", "房屋类型"))
        self.label_38.setText(_translate("MainWindow", "详细地址"))
        self.label_39.setText(_translate("MainWindow", "房型"))
        self.label_40.setText(_translate("MainWindow", "交通"))
        self.label_41.setText(_translate("MainWindow", "面积"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "普通住宅"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "公寓"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "平房"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "别墅"))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "其他"))
        self.label_42.setText(_translate("MainWindow", "区域"))
        self.label_43.setText(_translate("MainWindow", "建造年代"))
        self.label_44.setText(_translate("MainWindow", "楼层"))
        self.label_45.setText(_translate("MainWindow", "售价"))
        self.lineEdit_2.setText(_translate("MainWindow", "单独给出会根据所给的信息含有的关键字查询相关房源"))
        self.pushButton_7.setText(_translate("MainWindow", "查询"))
        self.label_6.setText(_translate("MainWindow", "用户名"))
        self.Setup()

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.need_num = 0
        self.house_num = 0
        self.dingdan_num = 0
        self.name = ''
        self.power = 0
        self.lib = []
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'config', port=3307, charset='utf8')
            cursor = db.cursor()
            sql = "select * from config.需求表个数"
            cursor.execute(sql)
            result = cursor.fetchall()
            self.need_num = result[0][0]
            self.house_num = result[0][1]
            self.dingdan_num = result[0][2]
            db.close()
        except:
            print('init error')
        self.get_lib()

    def slot_set_page(self, num):
        self.stackedWidget.setCurrentIndex(num)
        if num == 3:
            self.get_data_message()
            print('刷新信息')
        elif num == 4:
            self.get_house_messgae()
            print('刷新信息')

    def slot_delitem(self):
        d = self.listWidget.currentRow()
        if d != -1:
            item = self.listWidget.takeItem(d)
            num = self.house[item.text()][11]
            del self.house[item.text()]
            try:
                db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
                cursor = db.cursor()
                sql = "update house.house set 状态=1 WHERE 编号=%d" % (num)
                cursor.execute(sql)
                db.commit()
                db.close()
            except:
                print('slot_delitem error')
                db.rollback()

        d = self.listWidget.currentRow()
        if d == -1:
            self.lineEdit_5.setText('')
            self.lineEdit_9.setText('')
            self.lineEdit_4.setText('')
            self.lineEdit_10.setText('')
            self.lineEdit_6.setText('')
            self.lineEdit_11.setText('')
            self.lineEdit_7.setText('')
            self.lineEdit_12.setText('')
            self.lineEdit_8.setText('')
            self.lineEdit_3.setText('')


    def slot_delitem_2(self):
        d = self.listWidget_2.currentRow()
        if d != -1:
            item = self.listWidget_2.takeItem(d)
            tmp = self.message[item.text()]
            del self.message[item.text()]
            if tmp[4] != '订单通知':
                try:
                    db = pymysql.connect('localhost', 'root', '123456', 'user', port=3307, charset='utf8')
                    cursor = db.cursor()
                    sql = "update user.user_message set 状态=1 WHERE 编号=%d" % (tmp[6])
                    cursor.execute(sql)
                    db.commit()
                    db.close()
                except:
                    print('slot_delitem_2 error')
                    db.rollback()

    def slot_itemread(self, item):
        self.textEdit.setText(self.message[item .text()][2])

    def slot_up(self):
        d = self.listWidget_2.currentRow()
        self.listWidget_2.insertItem(d - 1, self.listWidget_2.takeItem(d))
        self.listWidget_2.setCurrentRow(d-1)

    def slot_down(self):
        d = self.listWidget_2.currentRow()
        self.listWidget_2.insertItem(d + 1, self.listWidget_2.takeItem(d))
        self.listWidget_2.setCurrentRow(d+1)

    def slot_sort_2(self, index):
        try:
            s = self.comboBox_28.itemText(index)
            self.listWidget_2.clear()
            result = list(self.message.values())
            if s == '时间':
                result.sort(key=lambda result: result[3])
            elif s == '未完成订单':
                result.sort(key=lambda result: result[4] == '订单通知', reverse=True)
            elif s == '用户':
                result.sort(key=lambda result: result[4] == '个人信息', reverse=True)
            elif s == '完成订单':
                result.sort(key=lambda result: result[4] == '完成订单', reverse=True)
            for i in result:
                self.listWidget_2.addItem(QtWidgets.QListWidgetItem(i[8]))
        except:
            print('slot_sort_2 error')

    def slot_sendneed(self):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
            cursor = db.cursor()
            Time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            sql = "insert into house.need(区域, 房屋类型, 售价, 建造年代, 面积, 房型, 楼层, 朝向, 交通, 状态, 时间, 编号) VALUE ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s', '%s', %d);" % (
            self.comboBox_2.currentText(), self.comboBox.currentText(), self.comboBox_3.currentText(),
            self.comboBox_7.currentText(), self.comboBox_5.currentText(), self.comboBox_8.currentText(),
            self.comboBox_6.currentText(), self.comboBox_9.currentText(), self.comboBox_10.currentText(),
            '0', Time, self.need_num)
            cursor.execute(sql)
            db.commit()
            str = '%s 的新需求订单 %d' % (Time, self.dingdan_num)
            self.send_dingdan(self.name, '', str, '订单通知', Time, self.need_num)
            self.need_num += 1
            self.update_num('需求表个数')
            print('success')
            QMessageBox.question(self, "提醒", '上传成功', QMessageBox.Yes | QMessageBox.No)
        except:
            print('slot_sendneed error')
            db.rollback()
        db.close()

    def slot_send(self):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
            cursor = db.cursor()
            Time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            sql = "insert into house.house(区域, 房屋类型, 售价, 建造年代, 面积, 房型, 楼层, 朝向, 交通, 详细地址, 状态, 编号)  VALUE ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s',%d,%d);" % (
            self.comboBox_4.currentText(), self.comboBox_15.currentText(), self.comboBox_18.currentText(),
            self.comboBox_11.currentText(), self.comboBox_13.currentText(), self.comboBox_12.currentText(),
            self.comboBox_17.currentText(), self.comboBox_14.currentText(), self.comboBox_16.currentText(), self.lineEdit.text(), 0, self.house_num)
            cursor.execute(sql)
            db.commit()
            print('success')
            self.house_num += 1
            self.update_num('房源个数')
            QMessageBox.question(self, "提醒", '上传成功', QMessageBox.Yes | QMessageBox.No)
        except:
            print('slot_send error')
            db.rollback()
        db.close()

    def slot_set_house(self, item):
        res = self.house[item.text()]
        self.lineEdit_5.setText(res[0])
        self.lineEdit_9.setText(res[1])
        self.lineEdit_4.setText(res[2])
        self.lineEdit_10.setText(res[3])
        self.lineEdit_6.setText(res[4])
        self.lineEdit_11.setText(res[5])
        self.lineEdit_7.setText(res[6])
        self.lineEdit_12.setText(res[7])
        self.lineEdit_8.setText(res[8])
        self.lineEdit_3.setText(res[9])
        self.switch = True
        self.slot_set_ediable()

    def slot_back(self):
        d = self.listWidget.currentRow()
        if d != -1:
            item = self.listWidget.item(d)
            self.slot_set_house(item)

    def slot_set_ediable(self):
        if self.listWidget.currentRow() == -1:
            return
        self.set_switch()
        if self.switch:
            self.pushButton_3.setText('不可修改')
        else:
            self.pushButton_3.setText('修改')

    def slot_search(self):
        item = [
            self.comboBox_23.currentText(),self.comboBox_24.currentText(),self.comboBox_25.currentText(),
            self.comboBox_19.currentText(), self.comboBox_21.currentText(), self.comboBox_26.currentText(),
            self.comboBox_20.currentText(), self.comboBox_22.currentText(), self.comboBox_27.currentText(),
            self.lineEdit_2.text()
        ]
        self.search = check.Ui_MainWindow(item, self.lib)
        self.search.show()

    def slot_submit_dingdan(self, num):
        Time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        # print(num)
        s = "已经为您找到匹配房源， 房源信息如下:\n"
        for i in range(10):
            s += num[i] + ' '
        s += '\n订单号为 ' + str(num[12])
        self.send_dingdan(self.name, num[11], s, '完成订单', Time, num[13])

    def slot_check(self):
        d = self.listWidget_2.currentRow()
        if d != -1:
            item = self.listWidget_2.item(d)
            if not item.text().endswith('订单通知'):
                QMessageBox.warning(self, "提醒", '不是订单信息无法查询', QMessageBox.Yes | QMessageBox.No)
                return
            self.tmp = self.message[item.text()]
            res = self.tmp[7]
            user_name = self.tmp[0]
            try:
                db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
                cursor = db.cursor()
                sql = "select * from house.need WHERE 编号=%d" % (res)
                cursor.execute(sql)
                result = cursor.fetchall()[0]
                item = []
                for i in range(1, 10):
                    item.append(result[i])
                item.append('')
                self.window1 = check.Ui_MainWindow(item, self.lib, '订单')
                self.window1.set_user_name(user_name, self.tmp[6], self.tmp[7])
                self.window1.show()
                self.window1.clicked.connect(self.slot_submit_dingdan)
                db.close()
            except:
                print('slot_check error')

    def slot_display_dingdan(self):
        d = self.listWidget_2.currentRow()
        if d != -1:
            item = self.listWidget_2.item(d)
            if not item.text().endswith('订单通知'):
                QMessageBox.warning(self, "提醒", '不是订单信息无法打开', QMessageBox.Yes | QMessageBox.No)
                return
            self.tmp = self.message[item.text()]
            res = self.tmp[7]
            try:
                db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
                cursor = db.cursor()
                sql = "select * from house.need WHERE 编号=%d" % (res)
                cursor.execute(sql)
                result = cursor.fetchall()[0]
                item = []
                for i in range(1, 10):
                    item.append(result[i])
                item.append('')
                self.window2 = display_dingdan.Ui_MainWindow()
                self.window2.setup(item)
                self.window2.show()
                db.close()
            except:
                print('slot_check error')

    def slot_send_message(self, res):
        # print(res)
        Time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        self.send_dingdan(self.name, res[0], res[2], res[1], Time)

    def slot_open_send(self):
        self.window3 = send.Ui_MainWindow()
        self.window3.clicked.connect(self.slot_send_message)
        self.window3.show()

    def slot_acce_dingdan(self):
        d = self.listWidget_2.currentRow()
        if d != -1:
            item = self.listWidget_2.item(d)
            s = item.text()
            if not s.endswith('完成订单'):
                return
            res = self.message[s][7]
            print('res ',res)
            try:
                db = pymysql.connect('localhost', 'root', '123456', 'user', port=3307, charset='utf8')
                cursor = db.cursor()
                sql = "update user_message set 状态=1 WHERE 单号=%d" %(res)
                cursor.execute(sql)
                db.commit()
                db.close()
                print('success')
                QMessageBox.question(self, "提醒", '成功', QMessageBox.Yes | QMessageBox.No)
            except:
                print('slot_acce_dingdan error')
                db.rollback()

    def del_house(self, tmp):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
            cursor = db.cursor()
            sql = "update house.house set 状态=1 where 编号=%d" % (tmp)
            cursor.execute(sql)
            db.commit()
            db.close()
        except:
            print('del house error')
            db.rollback()

    def send_ok_house(self):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
            cursor = db.cursor()
            tmp = (
                self.lineEdit_5.text(),self.lineEdit_9.text(),self.lineEdit_4.text(),
            self.lineEdit_10.text(),self.lineEdit_6.text(),self.lineEdit_11.text(),
            self.lineEdit_7.text(),self.lineEdit_12.text(),self.lineEdit_8.text(),self.lineEdit_3.text())
            sql = "insert into house.ok_house(区域, 房屋类型, 售价, 建造年代, 面积, 房型, 楼层, 朝向, 交通, 详细地址) VALUE ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')" % tmp
            cursor.execute(sql)
            db.commit()
            db.close()
            self.lib.append(tmp)
            d = self.listWidget.currentRow()
            item = self.listWidget.takeItem(d)
            tmp = self.house[item.text()]
            del self.house[item.text()]
            self.del_house(tmp[11])
            QMessageBox.warning(self, "提醒", '确认成功', QMessageBox.Yes | QMessageBox.No)
        except:
            print('send_ok_house error')
            db.rollback()

    def Setup(self):
        self.message = {}
        self.house = {}
        self.switch = True
        self.listWidget_2.setSelectionMode(1)
        self.listWidget.setSelectionMode(1)
        self.listWidget_2.itemClicked.connect(self.slot_itemread)
        self.comboBox_28.currentIndexChanged.connect(self.slot_sort_2)
        self.setlis()
        self.pushButton_61.clicked.connect(self.slot_sendneed)
        self.pushButton_62.clicked.connect(self.slot_send)
        self.listWidget.itemClicked.connect(self.slot_set_house)
        self.set_switch()
        self.pushButton_3.clicked.connect(self.slot_set_ediable)
        self.pushButton_15.clicked.connect(self.slot_back)
        self.pushButton_18.clicked.connect(self.send_ok_house)
        self.pushButton_7.clicked.connect(self.slot_search)
        self.pushButton_4.clicked.connect(self.slot_check)

    def get_data_message(self):
        name = self.name
        try:
            self.listWidget_2.clear()
            db = pymysql.connect('localhost', 'root', '123456', 'user', port=3307, charset='utf8')
            cursor = db.cursor()
            if self.power == 0:
                sql = "select * from user.user_message WHERE (receiver='%s' AND 状态 = 0)" % (name)
            else:
                sql = "select * from user.user_message WHERE ((receiver='%s' OR receiver='') AND 状态=0)" % (name)
            cursor.execute(sql)
            result = cursor.fetchall()
            result = sorted(result, key= lambda result: result[3])
            for i in result:
                str = '%s 来自%s的%s' % (i[3], i[0], i[4])
                i = list(i)
                i.append(str)
                self.message[str] = i
                self.listWidget_2.addItem(QtWidgets.QListWidgetItem(str))
            db.close()
        except:
            print('get_data_message eroor')

    def setlis(self):
        self.set_combox('朝向', self.comboBox_14)
        self.set_combox('朝向', self.comboBox_9)
        self.set_combox('朝向', self.comboBox_22)
        self.set_combox('房屋类型', self.comboBox)
        self.set_combox('房屋类型', self.comboBox_15)
        self.set_combox('房屋类型', self.comboBox_24)
        self.set_combox('房型', self.comboBox_8)
        self.set_combox('房型', self.comboBox_12)
        self.set_combox('房型', self.comboBox_26)
        self.set_combox('建造年代', self.comboBox_7)
        self.set_combox('建造年代', self.comboBox_11)
        self.set_combox('建造年代', self.comboBox_19)
        self.set_combox('交通', self.comboBox_16)
        self.set_combox('交通', self.comboBox_10)
        self.set_combox('交通', self.comboBox_27)
        self.set_combox('楼层', self.comboBox_20)
        self.set_combox('楼层', self.comboBox_6)
        self.set_combox('楼层', self.comboBox_17)
        self.set_combox('面积', self.comboBox_13)
        self.set_combox('面积', self.comboBox_5)
        self.set_combox('面积', self.comboBox_21)
        self.set_combox('区域', self.comboBox_23)
        self.set_combox('区域', self.comboBox_4)
        self.set_combox('区域', self.comboBox_2)
        self.set_combox('售价', self.comboBox_25)
        self.set_combox('售价', self.comboBox_3)
        self.set_combox('售价', self.comboBox_18)


    def set_combox(self, str, combox):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'config', port=3307, charset='utf8')
            cursor = db.cursor()
            sql = 'select * from config.%s' % (str)
            cursor.execute(sql)
            result = cursor.fetchall()
            combox.clear()
            for i in result:
                combox.addItem(i[0])
            db.close()
        except:
            print('set_combox error')

    def send_dingdan(self, sender, receiver, message, title, Time, num=None):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'user', port=3307, charset='utf8')
            cursor = db.cursor()
            print(num)
            if title == '订单通知' or title == '完成订单':
                sql = "insert into user.user_message(sender, receiver, message, time, title, 状态, 编号, 单号) Value ('%s', '%s', '%s', '%s', '%s', %d, %d, %d)" % (
                    sender, receiver, message, Time, title, 0, self.dingdan_num, num)
            else:
                sql = "insert into user.user_message(sender, receiver, message, time, title, 状态, 编号, 单号) Value ('%s', '%s', '%s', '%s', '%s', %d, %d, %d)" % (
                    sender, receiver, message, Time, title, 0, self.dingdan_num, -1)
            print(sql)
            cursor.execute(sql)
            db.commit()
            db.close()
            self.dingdan_num += 1
            self.update_num('订单个数')
        except:
            print('send_dingdan error')
            db.rollback()

    def update_num(self, name):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'config', port=3307, charset='utf8')
            cursor = db.cursor()
            sql = "update config.需求表个数 set %s = %s + 1" % (name,name)
            cursor.execute(sql)
            db.commit()
            db.close()
        except:
            print('update_num error')
            db.rollback()

    def get_house_messgae(self):
        try:
            self.listWidget.clear()
            db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
            cursor = db.cursor()
            sql = "select * from house.house where 状态 = 0"
            cursor.execute(sql)
            result = cursor.fetchall()
            for i in result:
                s = '房源' + str(i[11])
                print(s)
                self.house[s] = i
                self.listWidget.addItem(QtWidgets.QListWidgetItem(s))
            db.close()
        except:
            print('get_house_message error')

    def set_switch(self):
        self.switch = not self.switch
        self.lineEdit_5.setEnabled(self.switch)
        self.lineEdit_9.setEnabled(self.switch)
        self.lineEdit_4.setEnabled(self.switch)
        self.lineEdit_10.setEnabled(self.switch)
        self.lineEdit_6.setEnabled(self.switch)
        self.lineEdit_11.setEnabled(self.switch)
        self.lineEdit_7.setEnabled(self.switch)
        self.lineEdit_12.setEnabled(self.switch)
        self.lineEdit_8.setEnabled(self.switch)
        self.lineEdit_3.setEnabled(self.switch)

    def get_lib(self):
        try:
            db = pymysql.connect('localhost', 'root', '123456', 'house', port=3307, charset='utf8')
            cursor = db.cursor()
            sql = "select * from house.ok_house"
            cursor.execute(sql)
            self.lib = cursor.fetchall()
            db.close()
            self.lib = list(self.lib)
        except:
            print('get_lib error')

import b_rc
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    UI = Ui_MainWindow()
    UI.show()
    sys.exit(app.exec_())